export default {
  "version": 1,
  "updated": "2026-06-12",
  "note": "بنك كلمات محليّ لألعاب دمج الحروف — بالإيموجي بلا صور خارجيّة. كلمات بسيطة تنفصل حروفها وتتّصل بسلاسة (بلا لا/شدّة).",
  "words": [
    { "id": "shams", "word": "شمس", "emoji": "☀️", "age_band": "4-6" },
    { "id": "qamar", "word": "قمر", "emoji": "🌙", "age_band": "4-6" },
    { "id": "bab", "word": "باب", "emoji": "🚪", "age_band": "4-6" },
    { "id": "qalam", "word": "قلم", "emoji": "✏️", "age_band": "4-6" },
    { "id": "asad", "word": "أسد", "emoji": "🦁", "age_band": "4-6" },
    { "id": "fil", "word": "فيل", "emoji": "🐘", "age_band": "4-6" },
    { "id": "najm", "word": "نجم", "emoji": "⭐", "age_band": "4-6" },
    { "id": "samak", "word": "سمك", "emoji": "🐟", "age_band": "4-6" },
    { "id": "alam", "word": "علم", "emoji": "🚩", "age_band": "4-6" },
    { "id": "jamal", "word": "جمل", "emoji": "🐫", "age_band": "4-6" },
    { "id": "dik", "word": "ديك", "emoji": "🐓", "age_band": "4-6" },
    { "id": "moz", "word": "موز", "emoji": "🍌", "age_band": "4-6" },
    { "id": "taj", "word": "تاج", "emoji": "👑", "age_band": "4-6" },
    { "id": "bahr", "word": "بحر", "emoji": "🌊", "age_band": "4-6" },
    { "id": "jabal", "word": "جبل", "emoji": "⛰️", "age_band": "4-6" },
    { "id": "namr", "word": "نمر", "emoji": "🐅", "age_band": "4-6" },
    { "id": "kalb", "word": "كلب", "emoji": "🐕", "age_band": "4-6" },
    { "id": "ward", "word": "ورد", "emoji": "🌹", "age_band": "4-6" },
    { "id": "thalj", "word": "ثلج", "emoji": "❄️", "age_band": "4-6" },
    { "id": "ayn", "word": "عين", "emoji": "👁️", "age_band": "4-6" },
    { "id": "bait", "word": "بيت", "emoji": "🏠", "age_band": "4-6" },
    { "id": "qalb", "word": "قلب", "emoji": "❤️", "age_band": "4-6" },
    { "id": "tuffah", "word": "تفاح", "emoji": "🍎", "age_band": "7-10" },
    { "id": "qitar", "word": "قطار", "emoji": "🚂", "age_band": "7-10" },
    { "id": "kitab", "word": "كتاب", "emoji": "📖", "age_band": "7-10" },
    { "id": "shajara", "word": "شجرة", "emoji": "🌳", "age_band": "7-10" },
    { "id": "miftah", "word": "مفتاح", "emoji": "🔑", "age_band": "7-10" },
    { "id": "saa", "word": "ساعة", "emoji": "⏰", "age_band": "7-10" },
    { "id": "hisan", "word": "حصان", "emoji": "🐎", "age_band": "7-10" },
    { "id": "farasha", "word": "فراشة", "emoji": "🦋", "age_band": "7-10" },
    { "id": "battikh", "word": "بطيخ", "emoji": "🍉", "age_band": "7-10" },
    { "id": "inab", "word": "عنب", "emoji": "🍇", "age_band": "7-10" },
    { "id": "matar", "word": "مطر", "emoji": "🌧️", "age_band": "7-10" },
    { "id": "qamar2", "word": "نخلة", "emoji": "🌴", "age_band": "7-10" },
    { "id": "sahm", "word": "سهم", "emoji": "🏹", "age_band": "7-10" },
    { "id": "jisr", "word": "جسر", "emoji": "🌉", "age_band": "7-10" },
    { "id": "yad", "word": "يد", "emoji": "✋", "age_band": "4-6" },
    { "id": "fam", "word": "فم", "emoji": "👄", "age_band": "4-6" },
    { "id": "nar", "word": "نار", "emoji": "🔥", "age_band": "4-6" },
    { "id": "khubz", "word": "خبز", "emoji": "🍞", "age_band": "4-6" },
    { "id": "laban", "word": "لبن", "emoji": "🥛", "age_band": "4-6" },
    { "id": "asal", "word": "عسل", "emoji": "🍯", "age_band": "4-6" },
    { "id": "dub", "word": "دب", "emoji": "🐻", "age_band": "4-6" },
    { "id": "far", "word": "فأر", "emoji": "🐭", "age_band": "4-6" },
    { "id": "hut", "word": "حوت", "emoji": "🐳", "age_band": "4-6" },
    { "id": "naml", "word": "نمل", "emoji": "🐜", "age_band": "4-6" },
    { "id": "jazar", "word": "جزر", "emoji": "🥕", "age_band": "4-6" },
    { "id": "khawkh", "word": "خوخ", "emoji": "🍑", "age_band": "4-6" },
    { "id": "jubn", "word": "جبن", "emoji": "🧀", "age_band": "4-6" },
    { "id": "kub", "word": "كوب", "emoji": "🥤", "age_band": "4-6" },
    { "id": "shay", "word": "شاي", "emoji": "🍵", "age_band": "4-6" },
    { "id": "tabl", "word": "طبل", "emoji": "🥁", "age_band": "4-6" },
    { "id": "barq", "word": "برق", "emoji": "⚡", "age_band": "4-6" },
    { "id": "nahr", "word": "نهر", "emoji": "🏞️", "age_band": "4-6" },
    { "id": "thurah", "word": "ذرة", "emoji": "🌽", "age_band": "4-6" },
    { "id": "basal", "word": "بصل", "emoji": "🧅", "age_band": "4-6" },
    { "id": "thawm", "word": "ثوم", "emoji": "🧄", "age_band": "4-6" },
    { "id": "qird", "word": "قرد", "emoji": "🐒", "age_band": "4-6" },
    { "id": "dofdaa", "word": "ضفدع", "emoji": "🐸", "age_band": "7-10" },
    { "id": "laymun", "word": "ليمون", "emoji": "🍋", "age_band": "7-10" },
    { "id": "sarukh", "word": "صاروخ", "emoji": "🚀", "age_band": "7-10" },
    { "id": "arnab", "word": "أرنب", "emoji": "🐰", "age_band": "7-10" },
    { "id": "khiyar", "word": "خيار", "emoji": "🥒", "age_band": "7-10" },
    { "id": "sarir", "word": "سرير", "emoji": "🛏️", "age_band": "7-10" },
    { "id": "jawrab", "word": "جورب", "emoji": "🧦", "age_band": "7-10" },
    { "id": "fulful", "word": "فلفل", "emoji": "🌶️", "age_band": "7-10" },
    { "id": "ghayma", "word": "غيمة", "emoji": "☁️", "age_band": "7-10" },
    { "id": "shamaa", "word": "شمعة", "emoji": "🕯️", "age_band": "7-10" },
    { "id": "nazzara", "word": "نظارة", "emoji": "👓", "age_band": "7-10" }
  ],
  "wheel_letters": ["ب", "ت", "ث", "ج", "ح", "د", "ر", "س", "ش", "ع", "ف", "ق", "ك", "ل", "م", "ن", "ه", "و", "ي", "ا"]
}
